### ISSUE TITLE
submodlues foler is empty

### ISSUE THREAD

**Issue by sebastianwachter** [BlackRosie/PokemonGoNodeDashboard#2]
I just cloned the repo and the /submodlues folder is empty which leads to a failing installation.

**Comment by BlackRosie** [comment]
you have to pull the supmodule repo as wel,l i will add this to the install script soon

**Comment by BlackRosie** [comment]
@sebastianwachter  cd into the submodules folder and run git submodule update --init --recursive

**Comment by BlackRosie** [comment]
@sebastianwachter pushed a fix thanks for the heads up

**Comment by BlackRosie** [comment]
Fixed
